src/ChatApplication/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from homepage.views import home_page_view
from django.conf.urls.static import static
from django.conf import settings
from account.views import register_view,login_view,logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_page_view,name="home"),
    path('register/',register_view,name="register"),
    path('login/',login_view,name="login"),
    path('account/',include('account.urls',namespace='account')),
    path('logout/',logout_view,name="logout"),
]

#settings.DEBUG==True if we are in developement state
#settings.DEBUG==False if we are in production state

if settings.DEBUG:
    # goal:tell django where is static files
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

src/account/urls.py
from django.urls import path

from .views import account_view

app_name="account"

urlpatterns=[
    path('<user_id>/',account_view,name="view"),
]

src/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager

# for create super users and noraml users
class MyAccountManager(BaseUserManager):
      
      def create_user(self,phone,username,password=None):
            if not phone:
                  raise ValueError("Users must have a phone number!")
            if not username:
                  raise ValueError("Users must have a username!")
            user=self.model(phone=phone,username=username)
            user.set_password(password)
            user.save(using=self._db)
            return user
      def create_superuser(self,phone,username,password):
            user=self.create_user(phone=phone,username=username,password=password)
            #make user `super`
            user.is_admin=True
            user.is_staff=True
            user.is_superuser=True
            user.is_active=True
            user.save(using=self._db)
            return user

def get_profile_image_path(self):
	return 'profile_images/' + str(self.pk) + '/profile_image.png'
def get_default_profile_image_path():
      return 'defaultPro.png'
      

class Account(AbstractBaseUser):
    username=models.CharField(max_length=25,unique=True)
    phone=models.CharField(max_length=11,unique=True)
    date_joined=models.DateTimeField(verbose_name="date joined",auto_now_add=True)
    last_login=models.DateTimeField(auto_now=True)
    profile_image=models.ImageField(max_length=255,upload_to=get_profile_image_path,null=True,blank=True,default=get_default_profile_image_path)
    hide_phone=models.BooleanField(default=True)
    #for personalizing django user mode
    is_admin=models.BooleanField(default=False)
    is_active=models.BooleanField(default=True)
    is_staff=models.BooleanField(default=False)
    is_superuser=models.BooleanField(default=False)

    #set manager to model
    objects=MyAccountManager()
    
    USERNAME_FIELD='phone'
    REQUIRED_FIELDS=['username']
    
    def __str__(self):
          return self.username
    
    def has_perm(self,perm,obj=None):
          return self.is_admin
    
    def has_module_perms(self,app_label):
          return True
    
    def get_profile_image_name(self):
          comp_path=str(self.profile_image)
          return comp_path[str(self.profile_image).index(f'profile_images/f{self.pk}/'):]
          
    

src/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from account.models import Account

class RegistrationForm(UserCreationForm):
	phone = forms.CharField(max_length=11, help_text='Required. Add a valid phone number.')

	class Meta:
		model = Account
		fields = ('phone', 'username', 'password1', 'password2', )

	def clean_phone(self):
		phone = self.cleaned_data['phone']
		if len(str(phone))!=11 or not str(phone).startswith("09"):
			raise forms.ValidationError('Invalid Phone Number Format')
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(phone=phone)
		except Account.DoesNotExist:
			return phone
		raise forms.ValidationError('Input phone is already in use.')

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except Account.DoesNotExist:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)    
    
class AccountAuthenticationForm(forms.ModelForm):

    #widget for making password hidden when writing
	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('phone', 'password')

	def clean(self):
		if self.is_valid():
			phone = self.cleaned_data['phone']
			password = self.cleaned_data['password']
			if not authenticate(phone=phone, password=password):
				raise forms.ValidationError("Invalid login")    

src/account/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth import login,authenticate,logout
from account.forms import RegistrationForm,AccountAuthenticationForm
from .models import Account
from django.conf import settings

def register_view(request, *args, **kwargs):
	user = request.user
	if user.is_authenticated: 
		return redirect('home')

	context = {}
	if request.POST:
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			phone = form.cleaned_data.get('phone')
			raw_password = form.cleaned_data.get('password1')
			account = authenticate(phone=phone, password=raw_password)
			login(request, account)
			destination = kwargs.get("next")
			if destination:
				return redirect(destination)
			return redirect('home')
		else:
			print(form)
			context['registration_form'] = form

	else:
		form = RegistrationForm()
		context['registration_form'] = form
	return render(request, 'account/register.html', context)

def login_view(request, *args, **kwargs):
	context = {}
	user = request.user
	if user.is_authenticated: 
		return redirect("home")

	destination = get_redirect_if_exists(request)
	
	if request.POST:
		form = AccountAuthenticationForm(request.POST)
		if form.is_valid():
			phone = request.POST['phone']
			password = request.POST['password']
			user = authenticate(phone=phone, password=password)

			if user:
				login(request, user)
				if destination:
					return redirect(destination)
				return redirect("home")

	else:
		form = AccountAuthenticationForm()

	context['login_form'] = form

	return render(request, "account/login.html", context)


def get_redirect_if_exists(request):
	redirect = None
	if request.GET:
		if request.GET.get("next"):
			redirect = str(request.GET.get("next"))
	return redirect

def logout_view(request):
	logout(request)
	return redirect("login")

def account_view(request,*arga,**kwargs):
	context={}
	user_id=kwargs.get("user_id")
	try:
		account=Account.objects.get(pk=user_id)
	except Account.DoesNotExist:
		return HttpResponse("account not found")
	if account:
		context['id']=account.id
		context['phone']=account.phone
		context['username']=account.username
		context['hide_phone']=account.hide_phone
		context['profile_image']=account.profile_image.url

		is_self=True
		is_friend=False
		user=request.user
		if user.is_authenticated and user!=account:
			is_self=False
		elif not user.is_authenticated:
			is_self=False
		
		context['is_self']=is_self
		context['is_friend']=is_friend
		context['BASE_URL']=settings.BASE_URL

		return render(request,"account/account.html",context)

src/homepage/views.py
from django.shortcuts import render,redirect

# Create your views here.
def home_page_view(request,*args,**kwargs):
    context={}
    if request.user.is_authenticated:
        return render(request,"homepage/home.html",context)
    return redirect('login')

src/homepage/templates/homepage/home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&display=swap" rel="stylesheet">
	<script src="https://kit.fontawesome.com/fbc0082036.js" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '../../../../../static/CSS/homeStyle.css' %}"/>
	<title>Home</title>
</head>
<body>
	<section id="sidebar">
		<a href="#" class="brand">
			<i class='bx far fa-comment-alt'></i>
			<span class="text brandName">Chat !</span>
		</a>
		<ul class="side-menu top">
			<li class="active">
				<a href="#">
					<i class='bx far fa-comment'></i>
					<span class="text">Private Chats</span>
				</a>
			</li>
			<li>
				<a href="#">
					<i class='bx far fa-comments'></i>
					<span class="text">Groups</span>
				</a>
			</li>
			<li>
				<a href="#">
					<i class='bx far fa-address-book'></i>
					<span class="text">Contacts</span>
				</a>
			</li>
		</ul>
		<ul class="side-menu">
			<li>
				<a href="{% url 'account:view' user_id=request.user.id%}">
					<i class='bx far fa-user-circle'></i>
					<span class="text">Account</span>
				</a>
			</li>
			<li>
				<a href="{% url 'logout' %}" class="logout">
					<i class="bx fa fa-sign-out"></i>
					<span class="text">Logout</span>
				</a>
			</li>
		</ul>
		<div class="side-menu">
			<input type="checkbox" id="switch-mode" hidden>
			<label for="switch-mode" class="switch-mode"></label>
		</div>
	</section>
	
	<section id="content">
		<nav>
			<i class="fa fa-bars bx bx-menu"></i>
			<form action="#">
				<div class="form-input">
					<input type="search" placeholder="Search Groups or Users ...">
				</div>
			</form>
            <a href="#" id="new-group">
                <i id="new-group-icon"class='bx far fa-plus'></i>
                <span id="new-group-text">New Group</span>
            </a>
			<a href="#" class="notification">
				<i class='bx far fa-bell'></i>
				<span class="num">8</span>
			</a>
			<a href="{% url 'account:view' user_id=request.user.id%}" class="profile">
				<img src="{{request.user.profile_image.url}}">
			</a>
		</nav>
        <main style="display: flex;flex-direction: row;">
            <div id="show">
                <ul>
                </ul>
            </div>
            <div id="chat">

            </div>
		
		</main>
	</section>
	<script src="{% static '../../../../../static/JS/homeJS.js' %}"></script>
</body>
</html>

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>main</title>
    
<body>
    {% include 'header.html' %}
    {% include 'baseStyle.html' %}
    <div>
        {% block content %}

        {% endblock content %}
    </div>
</body>
</html>

src/templates/baseJS.html
<script type="text/javascript">

</script>

src/templates/baseStyle.html
<style type="text/css">
    head{
        font-family: Arial, Helvetica, sans-serif;
        font-weight: 300;
    }
    body{
        font-family: Arial, Helvetica, sans-serif;
        font-weight: 300;
        color: var(--text-color);
        background-color: #570A57;
    }
    :root{
        --purple-background-color:#570A57;
        --white-background-color:#EEEEEE;
        --text-color:#9C19E0;
    }
</style>

src/templates/header.html
<div>
    HEADER
</div>